---
startDelaySeconds: 0
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
- pattern: 'java.lang<type=OperatingSystem><>(CpuLoad|FreeMemorySize):'
  name: java_lang_OperatingSystem_$1
- pattern: 'java.lang<type=Memory><HeapMemoryUsage>used:'
  name: java_lang_Memory_HeapMemoryUsage_used
- pattern: 'java.lang<type=Runtime><>Uptime:'
  name: java_lang_Runtime_Uptime
